---
exclude: ['README.markdown', 'Makefile', 'component.json']
pygments: true
safe: false

name: 凝动夕阳 - 凝聚智慧力量，定焦最美夕阳
# url: http://wiredcraft.com
description: 凝聚智慧力量，定焦最美夕阳
author: xvfeng
email: xvfeng123@gmail.com
# ga: 'UA-XXXXXXX-X'